#!/usr/bin/env sh
# Generate the local service credentials used between the Gate and each dummy MCP service.
#
# The file lives outside Git (secrets/ is ignored) and is mounted read-only into the containers.
# Every service has its own scope, so the Gate presents a different token to each one and a single
# leaked scope cannot be replayed against another service.
#
# Re-running keeps existing tokens unless --force is given, so a restart does not invalidate the
# credentials the running containers were started with.
set -eu

root="$(cd "$(dirname "$0")/.." && pwd)"
target="${DEMO_CREDENTIALS_FILE:-$root/secrets/credentials.json}"
force="${1:-}"

if [ -f "$target" ] && [ "$force" != "--force" ]; then
    echo "credentials already exist: $target (use --force to regenerate)"
    exit 0
fi

mkdir -p "$(dirname "$target")"
umask 077

python3 - "$target" <<'PY'
import json
import secrets
import sys

target = sys.argv[1]
scopes = {name: {'gate-mcp': secrets.token_hex(32)}
          for name in ('documents', 'outbox', 'tickets')}
document = {
    'version': 1,
    'note': 'Local synthetic service credentials. Generated by scripts/demo-mcp-secrets.sh; never '
            'commit this file and never reuse these tokens outside a local stack.',
    'scopes': scopes,
}
with open(target, 'w', encoding='utf-8') as handle:
    json.dump(document, handle, indent=2, sort_keys=True)
    handle.write('\n')
print(f'wrote {target} with scopes: {", ".join(sorted(scopes))}')
PY

chmod 600 "$target"
